version: "3"

services:
  app-challenge-mutant:
    image: node:12-alpine
    command: yarn run watch-server
    working_dir: /app
    volumes:
      - .:/app/
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - challenge-mutant

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - challenge-mutant

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    environment:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - challenge-mutant

volumes:
  esdata:
    driver: local
networks:
  challenge-mutant:
